### ISSUE TITLE
bug: observability/trace flag is ignored

### ISSUE THREAD

**Issue by jprudent** [FunktionalIO/pillars#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a security issue?

- [X] This is not a security issue

### Which module is affected?

- [X] core
- [ ] db-doobie
- [ ] db-skunk
- [ ] db-migration
- [ ] docs
- [ ] flags
- [ ] http-client
- [ ] rabbitmq-fs2
- [ ] redis-rediculous

### Current Behavior

Traces are sent.    

### Expected Behavior

Traces are not sent

### Steps To Reproduce

given that config:
```
observability:
  enabled: true
  service-name: lobster
  metrics:
    enabled: true
  traces:
    enabled: false
```

run locally

traces are sent regularly 

### Environment

```markdown
- **JVM**:
- **Scala**:
- **Pillars**: latest
```
